#!/bin/bash

set -euo pipefail

# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"

if ! bash -c 'if ((BASH_VERSINFO[0] < 5)); then exit 2; fi'; then
  fatal "*** bash version 5+ is required; run script/bootstrap to fetch a newer bash ***" 1>&2
fi

if [[ $# -le 0 ]]; then
  set -- "test"
fi

exec \
  "$(dirname "$(dirname "$0")")"/test/bats/bin/bats \
  "$@"

# EOF
