#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"

assert_bash_is_new_enough

if [[ $# -le 0 ]]; then
  set -- "test"
fi

exec \
  "$(dirname "$(dirname "$0")")"/test/bats/bin/bats \
  "$@"

# EOF
