#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

# shellcheck source=./utilities.bash
source "$(dirname "$0")/utilities.bash"

header "Fetching utilites"

curl -sSfL \
  https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
  sh -s 'v1.21.0'

# vim: set ft=sh :
