#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail
source "$(dirname "$0")/utilities.bash"

header "Fetching utilites"
go get -u -v \
  github.com/alecthomas/gometalinter \
  github.com/mitchellh/gox

header "Installing gometalinter tools"
gometalinter --install

# vim: set ft=sh :
