#!/bin/bash
#
# Builds one (or more executable).
#
# Usage:
#   Just your native executable:
#      ./script/build
#   All cross compile platforms:
#      ./script/build all

set -euo pipefail
# shellcheck source=./utilities.bash
source "$(dirname "$0")/utilities.bash"

progname="chronic"

osarch="${1:-native}"
export CGO_ENABLED=0 # Force static compiling

version="$(git describe --tags || echo unreleased)"
ldflags="-s -w -X main.version=${version}"

function dogox()
{
  gox \
    -ldflags "$ldflags" \
    -osarch="$*" \
    -output="${progname}_{{.OS}}_{{.Arch}}"
}

if [[ "$osarch" == *all* ]]; then
  osarches=(
    darwin/amd64

    linux/amd64
    linux/386
    linux/ppc64le

    windows/amd64
    windows/386
  )

  header "Building all binaries"
  dogox "${osarches[*]}"
else
  header "Building native binary"
  go build \
    -ldflags "$ldflags" \
    -o "$progname" \
    ./*.go
fi

# vim: set ft=sh :
