#!/bin/bash
#
# Runs all tests.

set -euo pipefail
# shellcheck source=./utilities.bash
source "$(dirname "$0")/utilities.bash"

header "Test the CI configuration"
docker run \
  "--rm" \
  "--volume=${PWD}:/goapp" \
  "--env=RUN=1" \
  "--env=REPO=github.com/docwhat/chronic" \
  golangci/build-runner goenvbuild

# vim: set ft=sh :
