#!/usr/bin/env bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"

header "Golangci Linter"
golangci-lint run --verbose --config=.golangci.yml

if [[ -z ${CI:-} ]]; then
  header "Super Linter"
  docker run \
    --rm \
    --env=RUN_LOCAL=true \
    --env=VALIDATE_GO=false \
    --volume="${PWD}:/tmp/lint" \
    github/super-linter
fi

# vim: set ft=sh :
