#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail
# shellcheck source=./utilities.bash
source "$(dirname "$0")/utilities.bash"

header "Lint"
golangci-lint run ./...

# vim: set ft=sh :
