#!/bin/bash
#
# Runs all tests.

set -euo pipefail

# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"

header "Unit Tests"
go test -v

header "Functional Tests"
"$(dirname "$0")/bats"

# vim: set ft=sh :
