---
name: Lint Code Base

on: ["push", "pull_request"]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "bootstrap"
        run: |
          ./script/bootstrap

      - name: "lint"
        run: |
          ./script/lint

      - name: "super lint"
        uses: github/super-linter@v4.1.0
        env:
          VALIDATE_GO: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
