name: "Test Code 🧪"

on: ["push", "pull_request"]

jobs:
  test:
    name: "test"
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
        with:
          path: ./
          submodules: true

      - name: detect go version
        id: detect
        run: echo "::set-output name=go-version::$(grep "^go " go.mod | cut -d " " -f 2)"

      - name: "get go"
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.detect.outputs.go-version }}

      - name: "bootstrap"
        run: |
          ./script/bootstrap

      - name: test
        run: |
          ./script/test
